# file: roles/dotfiles/tasks/dan.yml

---
# files ------------------------------------------------------------------- {{{
- name: dan | mkdir -p dotfiles.dan.directories
  file: name={{ item }} state=directory
  with_items: '{{ dotfiles.dan.directories }}'

- name: dan | cp dotfiles.dan.templates
  template: src={{ item.src }} dest={{ item.dest }}
  with_items: '{{ dotfiles.dan.templates }}'
# /files ------------------------------------------------------------------ }}}

# repos ------------------------------------------------------------------- {{{
- name: dan | hg clone dotfiles.dan.hg.repos
  hg: repo={{ item.repo }} dest={{ item.dest }} executable={{ executables.hg }}
  with_items: '{{ dotfiles.dan.hg.repos }}'

- name: dan | git clone dotfiles.dan.git.repos
  git: repo={{ item.repo }} dest={{ item.dest }} accept_hostkey=true
  with_items: '{{ dotfiles.dan.git.repos }}'
# /repos ------------------------------------------------------------------ }}}
