# file: roles/dotfiles/tasks/dan.yml

---
# files ------------------------------------------------------------------- {{{
# - name: dan | sudo mkdir -p dotfiles.dan.sudo_directories
#   file: name={{ item }} state=directory
#   loop: '{{ dotfiles.dan.sudo_directories }}'
#   become: yes
#   become_method: su

- name: dan | mkdir -p dotfiles.dan.directories
  file: name={{ item }} state=directory
  loop: '{{ dotfiles.dan.directories }}'

- name: dan | cp dotfiles.dan.templates
  template: src={{ item.src }} dest={{ item.dest }}
  loop: '{{ dotfiles.dan.templates }}'

- name: dan | ln -s dotfiles.dan.links
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop: '{{ dotfiles.dan.links }}'
# /files ------------------------------------------------------------------ }}}

# databases --------------------------------------------------------------- {{{
- name: dan | createdb database 1
  postgresql_db: name={{ dan.user.name }} state=present

- name: dan | creatuser postgres
  postgresql_user: name=postgres state=present login_user={{ dan.user.name }} role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,REPLICATION,BYPASSRLS

- name: dan | createdb database 2
  postgresql_db: name={{ item }} state=present
  loop: "{{ dotfiles.dan.databases }}"
# /databases -------------------------------------------------------------- }}}

# repos ------------------------------------------------------------------- {{{
- name: dan | hg clone dotfiles.dan.hg.repos
  hg: repo={{ item.repo }} dest={{ item.dest }} executable={{ executables.hg }}
  loop: '{{ dotfiles.dan.hg.repos }}'

- name: dan | git clone dotfiles.dan.git.repos
  git: repo={{ item.repo }} dest={{ item.dest }} accept_hostkey=true
  loop: '{{ dotfiles.dan.git.repos }}'
# /repos ------------------------------------------------------------------ }}}

# rbenv ------------------------------------------------------------------- {{{
# - name: dan | rbenv install dotfiles.dan.ruby.version
#   shell: "{{ dotfiles.dan.rbenv.commands.rbenv_install_ruby }}"
# 
# - name: dan | rbenv global dotfiles.dan.ruby.version
#   shell: "{{ dotfiles.dan.rbenv.commands.rbenv_global_ruby }}"
# 
# - name: dan | gem install bundler
#   shell: "{{ dotfiles.dan.rbenv.commands.gem_install_bundler }}"
# /rbenv ------------------------------------------------------------------ }}}

# dotfiles ---------------------------------------------------------------- {{{
# - name: dan | rake install dotfiles
#   shell: "{{ dotfiles.dan.dotfiles.commands.install }}"

# - name: dan | ln -s ~/.tmux.system.conf ~/.tmux.conf
#   file: "src={{ dan.home }}/.tmux.{{ system }}.conf dest={{ dan.home }}/.tmux.conf state=link"
# /dotfiles --------------------------------------------------------------- }}}
